---
layout: cv
title: Austin Bitsoi's CV
---
# Austin Bitsoi
Juvenile Detention Officer, Student at BYUI, Data Science Major

<div id="webaddress">
<a href="https://abitsma.github.io/anterogradetragedy/">Music I'm working on</a>
| <a href="https://www.eastidahonews.com/2018/09/gravesite-of-u-s-soldier-gets-facelift-140-years-after-his-death-and-now-its-being-rededicated/">A cool project I've done</a>
</div>


## Currently

Full time Data Science Student, Part time Juvenile Detention Officer

### Specialized in

Python, professional communications. 


### Research interests

Game Theory, Maladaptive Behavior in Juveniles, Anger Management for Juveniles.


## Education

`2017-2021`
__Rigby High School, Rigby__

`2024 - now`
__BYU-Idaho, Rexburg__


## Awards

`2018`
Eagle Scout Award

`2021`
Graduated Rigby High School with High Honors

`2024`
INL Scholarship reward
BYU-I Scholarship reward


## Occupations

`2024-now`
__Juvenile Detention Officer__, 5 County Juvenile Detention Center

- Peace Officer
- First Responder

`2024`
__Car Wash Attendant__, Tagg-N-Go

- Washed 10,000+ cars
- Adapted practices to ensure safety

`2019-2021`
__Crop Consultant Assistant__, Kelly Hurst Agricultural Consulting, Inc.

- Data collection on potato crops
- Suggested practices to produce highest yeild for crops

`2017-2019`
__Private Property Manager__, Early Bird Landscaping

- Utilized a learned set of skills in sprinkler work and landscaping
- Kept a proactive list of problems and accomplished solutions within a given time frame. 



<!-- ### Footer

Last updated: May 2013 -->